### ISSUE TITLE
Application crashes if there are no incidents selected and commands are issued against it.

### ISSUE THREAD

**Issue by iamkirkbater** [clcollins/srepd#52]
If you open the application and there are no PD incidents on the board, and you hit "l" it will crash.

```
panic: runtime error: index out of range [1] with length 0

goroutine 67 [running]:
github.com/clcollins/srepd/pkg/tui.switchTableFocusMode.func9()
        /Users/kbater/Projects/clcollins/srepd/pkg/tui/msgHandlers.go:146 +0xac
github.com/charmbracelet/bubbletea.(*Program).eventLoop.func1()
        /Users/kbater/Projects/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:381 +0x5c
created by github.com/charmbracelet/bubbletea.(*Program).eventLoop in goroutine 1
        /Users/kbater/Projects/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:374 +0x380
```
        
  The login, acknowledge, silence, add note, and open in browser functions all crash. Expected functionality would be similar to when you hit "Enter" and it shows an error message:
  
  ```
╭────────────────────────────────────────────────────────────────╮
│                                                                │
│   •ERROR•                                                      │
│                                                                │
│   no incident selected                                         │
│                                                                │
╰────────────────────────────────────────────────────────────────╯
esc back • q/ctrl+c quit
```

**Comment by clcollins** [comment]
Duplicates #50
